package it.polimi.deib.mattiaSalnitri.swing_07_esPolizia;

import javax.swing.*;
import java.util.Vector;

/**
 * class that manages the alarms generated by the event of the main frame
 */
public class AlarmHandler {

    //reference to the text area where to write the volanti
    JTextArea alertsTA;

    //the manager of the volanti
    VolanteManager vm;

    /**
     * the constructor of the class
     * @param alertsTA the text area where to write the names of the volanti
     */
    public AlarmHandler(JTextArea alertsTA)
    {
        this.alertsTA=alertsTA;

        this.vm = new VolanteManager();

        vm.addVolante(new Volante("v1.1",2),1);
        vm.addVolante(new Volante("v1.2",3),1);

        vm.addVolante(new Volante("v2.1",3),2);
        vm.addVolante(new Volante("v2.2",3),2);
        vm.addVolante(new Volante("v2.3",3),2);

        vm.addVolante(new Volante("v3.1",3),3);

        vm.addVolante(new Volante("v4.1",3),4);
        vm.addVolante(new Volante("v4.2",3),4);
        vm.addVolante(new Volante("v4.3",3),4);
        vm.addVolante(new Volante("v4.4",3),4);

        vm.addVolante(new Volante("v5.1",3),5);

    }

    /**
     * Prints the text area the names of the volanti in a given zone
     * @param zone the zone to search
     */
    public void setAlarm(String zone)
    {
        Vector<Volante> volanti;

        switch(zone) {
            case "1":
                volanti = vm.getVolantiZone(1);
                break;
            case "2":
                volanti = vm.getVolantiZone(2);
                break;
            case "3":
                volanti = vm.getVolantiZone(3);
                break;
            case "4":
                volanti = vm.getVolantiZone(4);
                break;
            case "5":
                volanti = vm.getVolantiZone(5);
                break;
            default:
                volanti = vm.getVolantiZone(6);
        }

        for (Volante v : volanti)
            alertsTA.append(v.getName()+"\n");

    }

}
